version: '3'
services:
  backend:
    build: ./congress-tracker-backend
    ports:
      - "5001:5001"
  frontend:
    build: ./congress-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
