version: '3'
services:
  backend:
    build: ./congress-tracker-backend
    ports:
      - "5001:5001"
    volumes:
      - ./billtrack-a2369-72eca0fdbb6d.json:/app/billtrack-a2369-72eca0fdbb6d.json:ro
  frontend:
    build: ./congress-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
